### ISSUE TITLE
Field Operations

### ISSUE THREAD

**Issue by twhite313** [Esri/esri-eds#356]
## Overview
https://main--esri-eds--esri.aem.page/en-us/capabilities/field-operations/overview
- [x] Content below banner needs formatting. Should be content block and Case Study Hero
- [x] Card block styles
- [x] Media splits not in blocks

## Get Started
https://main--esri-eds--esri.aem.page/en-us/capabilities/field-operations/get-started
- [x]  Text blocks at top, below banner
- [x] cards formatting - URL showing
