### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by twhite313** [Esri/esri-eds#359]
## Overview

- [x] Font in banner looks like wrong glyph/weight
- [x] Storyteller layout a bit off. Button size & color; video playback
- [x] Double banner
- [x] Tabs content panel too tall, background distorted
- [x] #381
- [x] #372

## Company

- [x] TLS Icon missing icons
- [x] Storyteller (see above)
- [x] Card Standard heading misaligned, spacing off
- [x] Card standard URL showing, styles missing (border, etc)
- [x] #555

## Technology

- Banner, Storyteller: same as others
- [x] Header above cards should be centered, bold
- [x] Tab icon issue (known)
