### ISSUE TITLE
About Locations Section

### ISSUE THREAD

**Issue by twhite313** [Esri/esri-eds#360]
https://main--esri-eds--esri.aem.live/en-us/about/about-esri/locations

Documents in `/about-esri/` folder, but also `about-esri/[locaction]/overview`. Europe in particular. 

## Locations

Previously mentioned banner font issues, potential size issue
- [x] #365
- [x] #586
- [x] #503
- [ ] Link to Europe hard coded to www.esri.com
- [ ] Link to MEA hard coded to www.esri.com

## Americas

- [x] #545
- [x] TLS Icon spacing is off, not centered
- [x] Mosaic Review copy is large, but matches live site. Two diff sizes of copy to account for. 
- [x] CCS backgrounds too big
- [x] #546
- [x] Tabs header above should be centered
- [x] Tabs cards ragged heights
- [x] Cards in New about section missing styles. Standard Cards 6 across
- [x] #581
- [x] #388
- [x] #582

## Asia Pacific

Same as above

## Europe
Map works correctly
Prod: **https://www.esri.com/en-us/about/about-esri/europe/overview**
Live: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/europe/overview

- [ ] In a subfolder in documents
- [x] Theme colors showing in content bars
- [x] Cards not rendering correctly
- [x] #583
- [x] #584

## MEA 

Map looks mostly correct, but shorter than Europe. 
Same issues as Americas, et al.

**Comment by twhite313** [comment]
Closing as complete. 

The hard coded links are a content issues. As is the subfolder.
