### ISSUE TITLE
Capabilities / Spatial Analytics Data Science

### ISSUE THREAD

**Issue by jsavella** [Esri/esri-eds#363]
**Issues for all documents in the /capabilities/spatial-analytics/??? folder**

### Overview

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/spatial-analytics-data-science/overview

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level.
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden. 
- [x] #413
- [x] HERO BANNER: background image needs to keep its aspect ratio. It's compressed horizontally. 
- [x] HERO BANNER: cta button is blue needs to white with arrow icon. 
- [x] STORYTELLER: extra padding with first content paragraph right below content title. 
- [x] STORYTELLER: Content subtitles need to be an ordered list with '0' prefix. 
- [x] STORYTELLER: video mp4 url is visible. Needs to be hidden. Don't see mp4 as background animated video.
- [x] STORYTELLER: foreground image overlay text content is below foreground image. Should be within foreground image at it's bottom with a semi-transparent dark box. 
- [ ] DEFAULT CONTENT WRAPPER: Title content and paragraph content needs to be center aligned and
- [x]  padding-leader-# css properties added to codebase. 
- [x] CARDS: missing icons. 
- [x] CARDS: reduce margin between title and paragraph content below title. 
- [x] CARDS are two rows (3 top/2 bottom). www has all 5 cards in one row.  
- [x] DEFAULT CONTENT WRAPPER: icon is too small. www is at 96px width 96px height:  
- [x] FORM: missing

### Analytics

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/spatial-analytics-data-science/analytics

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level.
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden.
- [x] LOCAL NAV: www has a blue 'Get Started' button. Need to add css to account for this authored element. 
- [x] STORYTELLER: extra padding with first content paragraph right below content title. 
- [x] STORYTELLER: Content subtitles need to be an ordered list with '0' prefix. 
- [x] STORYTELLER: video mp4 url is visible. Needs to be hidden. Don't see mp4 as background animated video. 
- [x] STORYTELLER: foreground image overlay text content is below foreground image. Should be within foreground image at it's bottom with a semi-transparent dark box. 
- [ ] SECTION: Title content and paragraph content needs to be center aligned and 
- [x] padding-leader-# css properties added to codebase. 
- [x] TABS: large icon image. 
- [x] CARDS: CTA is a blue calcite button. Should be a blue link with arrow and underline. 
- [x] CARDS-CARD-BODY: Title needs more bottom margin space ~10px. 
- [x] FORM: missing

**Comment by twhite313** [comment]
Content bar issue should resolve the remaining issues here.
