### ISSUE TITLE
Capabilities / Realtime

### ISSUE THREAD

**Issue by jsavella** [Esri/esri-eds#364]
**Issues for all documents in the /capabilities/realtime/??? folder**

### Overview

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/overview

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level.
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV: menu titles wrap. Text wrapping needs to be disabled 
- [x] LOCAL NAV. title has white background therefore appears to be hidden. 
- [x] HERO BANNER: Title needs a max-width of 500px. 
- [x] CARDS: missing icons; 
- [x] CARDS: no box border visible. 
- [x] CARDS: card url is visible, needs to be hidden. 
- [x] CARDS: not interactive nor hyperlinked nor is there a hover effect. 
- [ ] #612
- [x] #390
- [x] ELASTIC CONTENT STRIP: title and subtitle currently have hover effect. need it removed. 
- [x] #391
- [x] ELASTIC CONTENT STRIPT: subtitle needs to be white text. 
- [ ] CTA: broken. needs JS to allow for contact sales variant with phone #, chat online box and contact sales team box. 

### Get Started / features/actuation / features/analysis / features/dissemination / features /ingestion / features/storage / features/visualization 

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/get-started
URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/features/actuation
URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/features/analysis
URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/features/dissemination
URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/features/ingestion
URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/features/storage
URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/features/visualization

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level.
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV: menu title is blank. www has a menu title. 
- [x] LOCAL NAV: Text wrapping needs to be disabled 
- [x] LOCAL NAV. title has white background therefore appears to be hidden. 
- [x] HERO BANNER: Title needs a max-width of 500px. 
- [x] DEFAULT CONTENT WRAPPER: Title content and paragraph content needs to be center aligned and grid system css properties added to codebase.  
- [x] CARDS: Title needs more bottom margin spacing: ~10px. 
- [x] CARDS: both calcite buttons needs to be converted to calcite links. 
- [ ] CTA: broken. needs js to allow for contact sales variant with phone #, chat online box and contact sales team box.

## Features/Analysis

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/features/actuati

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level.
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV: menu title is blank. www has a menu title. 
- [x] LOCAL NAV: Text wrapping needs to be disabled. 
- [x] LOCAL NAV: title has white background on table view therefore appears to be hidden. 
- [x] HERO BANNER: Title needs a max-width of 500px. 
- [x] DEFAULT CONTENT WRAPPER: Title content and paragraph content needs to be left aligned and grid system css properties added to codebase. 
- [x] 50-50: need a left gutter of left margin. Current text content is flush with left edge.  Same for right variant.
- [x] 50-50: calcite buttons need to be switched to calcite links or underline links. 
- [ ] #611

### Partners/Service

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/partners/service

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level.
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Get Started' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV: menu titles wrap. Text wrapping needs to be disabled. 
- [x] DEFAULT CONTENT WRAPPER: Title content and paragraph content needs to be center aligned and 
- [x] padding-leader-# css properties added to codebase. 
- [x] TABS: large icon image. 
- [x] CARDS: CTA is a blue calcite button. Should be a blue link with arrow and underline. 
- [x] CARDS-CARD-BODY: jpg image is too large. 
- [x] CARDS-CARD-BODY: entire cards needs to be enclosed in square border. 
- [ ] CALL-TO-ACTION: need the ability to author phones numbers or contact sales variant w/ 1column - phone number/opening hours/link, 2nd column - chat online box, 3rd column - contact the sales team box.

### Partners/cloud-iot-platforms
URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/partners/cloud-iot-platforms

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level.
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV: menu titles wrap. Text wrapping needs to be disabled. 
- [x] HERO BANNER: Title needs a max-width of 500px. 
- [x] DEFAULT CONTENT WRAPPER: Title content and paragraph content needs to be left aligned and grid system css properties added to codebase. 
- [x] MEDIA SPLIT: when content is in left half of component, there is no margin to it's left or no left gutter.
