### ISSUE TITLE
Digital Twin

### ISSUE THREAD

**Issue by ahenriksen-fedx** [Esri/esri-eds#368]
Issues for all documents in the `/digital-twin/` folder.

### Overview

URL: https://main--esri-eds--esri.aem.live/en-us/digital-twin/overview
PRD: https://www.esri.com/en-us/digital-twin/overview

- [x] Local Navigation: The width is incorrect. Heading and buttons should be aligned with content.
- [x] Hero Banner: Missing animation/video.
- [x] Storyteller: Still needs work. Image sizes, padding, and alignment are still off.
- [x] General: All components need margins at the top/bottom so they don't sit on top of one another.
- [x] Section: Basic text blocks are too wide.
- [x] Tabs: Issue with icons.
- [x] Content Container: Missing icon on CTA buttons.
- [x] Cards: All of the cards look completely broken and/or unfinished.
- [x] One Form: Missing form at the bottom of the page.
