### ISSUE TITLE
Digital Transformation

### ISSUE THREAD

**Issue by ahenriksen-fedx** [Esri/esri-eds#369]
Issues for all documents in the `/digital-transformation/` folder.

### Overview

URL: https://main--esri-eds--esri.aem.live/en-us/digital-transformation/overview
PRD: https://www.esri.com/en-us/digital-transformation/overview

- [x] Local Navigation: The width is incorrect. Heading and buttons should be aligned with content.
- [x] Hero Banner: Missing animation/video.
- [x] Storyteller: Still needs work. Image sizes, padding, and alignment are still off.
- [x] General: All components need margins at the top/bottom so they don't sit on top of one another.
- [x] Tabs: Issue with icons.
- [ ] Tabs: Missing icon on CTA buttons.
