### ISSUE TITLE
Capabilities / Mapping 

### ISSUE THREAD

**Issue by jsavella** [Esri/esri-eds#374]
**Issues for all documents in the /capabilities/mapping/? folder**

# Overview

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/mapping/overview

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level.
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV. title has white background therefore appears to be hidden. 
- [x] HERO BANNER: Title needs a max-width of 500px. 
- [x] 50-50: need a left gutter of left margin. Current text content is flush with left edge.  Same for right variant.
- [x] 50-50: calcite buttons need to be switched to calcite links or underline links. 
- [x] IMAGE SWITCHER: missing image content with content bar which contains title, info paragraph and link. 
- [x] CARDS: links need to be hidden. 
- [x] CARDS: need outline around card: 
- [x] CARDS: title needs to be an h2 tag. 
- [x] FORM: visually broken. meta data needs to be visually hidden. 
- [x] CTA: 5 variants needs to be addressed. 

### Smart-mapping

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/mapping/smart-mapping

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level.
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV. title has white background therefore appears to be hidden. 
- [x] HERO BANNER: subtitle needs to be an h3. 
- [x] HERO BANNER: Title needs a max-width of 500px. 
- [x] MEDIA TEXT SPLIT: left image should not span 50% of page width. Add margin on all 4 sides of left image. 
- [x] MEDIA TEXT SPLIT: hide video url and add play button feature
- [x] CARDS: missing icon. 
- [x] CARDS: title font size too small needs to be at least an h2. Need text center styling. 
- [x] 50-50: need a left gutter of left margin. Current text content is flush with left edge. 
- [x] MEDIA GALLERY: link needs to be hidden. 
- [x] MEDIA GALLERY: title and description missing.  
- [x] CARD SIMPLE: card missing outer border. 
- [x] #521
