### ISSUE TITLE
Capabilities / Imagery Remote Sensing

### ISSUE THREAD

**Issue by jsavella** [Esri/esri-eds#378]
**Issues for all documents in the /capabilities/imagery-remote-sensing/??? folder**

### Overview

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/overview

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level. 
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] #383
- [x] HERO BANNER: Title needs a max-width of 500px. 
- [x] HERO BANNER: foreground image cropped on left and right sides.
- [x] STORYTELLER: foreground image overlay text needs more top margin. 
- [x] STORYTELLER: more spacing between title and description in foreground image overlay text. 
- [x] CORE EMBED: video mediaspace url implementation. see www. ESRI TEXT CARD: center text with icon. 
- [x] ESRI TEXT CARD: update icon color to blue #009af2 --color-theme. 
- [x] TABS: local nav is visible to far right of tabs component. 
- [x] TABS: icons placement. centered and above title for each tab. 
- [x] TABS: cta must be left justified and line up with title/category and description above it. 
- [x] MEDIA GALLERY: align images horizontally. 
- [x] MEDIA GALLERY: hide url. 
- [x] MEDIA GALLERY: gallery of images need to adjust to given grid size at different viewport sizes. 
- [x] CARDS: icons missing. 
- [x] FORM: hide form meta data.

### Resources

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/resources

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level. 
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV. title has white background therefore appears to be hidden. 
- [x] #563
- [x] CARDS: links need to be hidden. 
- [x] CARDS: need outline around card: 
- [x] CARDS: title needs to be an h2 tag. 
- [x] TABS: icons placement. centered and above title for each tab. 
- [x] TABS: cta must be left justified and line up with title/category and description above it. 
- [x] CARD SIMPLE: card missing outer border. 
- [x] CARD SIMPLE: align icon with title and description/add top margin; 
- [x] 50-50: need a left gutter of left margin. Current text content is flush with left edge. Same for right variant.  
- [x] #566

### Capabilities / Content
Pages are similarly structured

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/capabilities/analysis
URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/capabilities/content

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level. 
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV: title has white background therefore appears to be hidden. 
- [x] STORYTELLER: foreground image overlay text needs more top margin. 
- [x] STORYTELLER: more spacing between title and description in foreground image overlay text.  
- [x] TABS: icons placement. centered and above title for each tab. 
- [x] IMAGE SWITCHER: missing image content with content bar which contains title, info paragraph and link. 
- [x] IMAGE SWITCHER: round images are not completely round. currently oval shaped. 
- [x] TEXT LINK STACK: icons are must be 48x48px. 
- [x] TEXT LINK STACK: reduce spacing between icon and title. 
- [x] TEXT LINK STACK: update icon color from white to blue #009af2.
- [x] #435
- [x] #564
- [x] CARD STANDARD: links need to be hidden.
- [x] CARDS STANDARD: need outline around card:
- [x] CARDS STANDARD: title needs to be an h2 tag.
- [x] FORM: hide form meta data.

# Capabilities / Management

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/capabilities/management

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level. 
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV: title has white background therefore appears to be hidden. 
- [x] STORYTELLER: foreground image overlay text needs more top margin. 
- [x] STORYTELLER: more spacing between title and description in foreground image overlay text.  
- [x] TABS: icons placement. centered and above title for each tab. 
- [x] IMAGE SWITCHER: missing image content with content bar which contains title, info paragraph and link. 
- [x] IMAGE SWITCHER: round images are not completely round. currently oval shaped. 
- [x] TEXT LINK STACK: icons are must be 48x48px. 
- [x] TEXT LINK STACK: reduce spacing between icon and title. 
- [x] TEXT LINK STACK: update icon color from white to blue #009af2.
- [x] QUOTE: update icon color to blue #009af2. 
- [x] QUOTE: adjust author title font-size to match job title.Increase size of quote description.  FORM: hide meta data.

# Capabilities / Mapping

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/capabilities/mapping

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level. 
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV: title has white background therefore appears to be hidden. 
- [x] HERO BANNER: update subtitle to an h3 and increase it's font size to --font-6. 
- [x] TEXT LINK STACK: icons are must be 48x48px. 
- [x] TEXT LINK STACK: reduce spacing between icon and title. 
- [x] TEXT LINK STACK: update icon color from white to blue #009af2. 
- [x] STORYTELLER: foreground image overlay text needs more top margin. 
- [x] STORYTELLER: more spacing between title and description in foreground image overlay text. 
- [x] STORYTELLER: background image height is larger than normal. 
- [x] TABS: icons placement. centered and above title for each tab. 
- [x] QUOTE: update icon color to blue #009af2. 
- [x] QUOTE: adjust author title font-size to match job title.Increase size of quote description. 
- [x] FORM: hide meta data

# Capabilities / Visualization Interpretation

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/capabilities/visualization-interpretation

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level. 
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV. title has white background therefore appears to be hidden. 
- [x] STORYTELLER: foreground image overlay text needs more top margin. 
- [x] STORYTELLER: more spacing between title and description in foreground image overlay text.  
- [x] TABS: icons placement. centered and above title for each tab.  
- [x] IMAGE SWITCHER: missing image content with content bar which contains title, info paragraph and link. 
- [x] #493
- [x] TEXT LINK STACK ICON: icons are must be 48x48px. 
- [x] TEXT LINK STACK ICON: reduce spacing between icon and title. 
- [x] TEXT LINK STACK ICON: update calcite button to calcite link.  
- [x] FORM: hide meta data
