### ISSUE TITLE
Capabilities / Indoor GIS

### ISSUE THREAD

**Issue by jsavella** [Esri/esri-eds#385]
**Issues for all documents in the /capabilities/indoor/??? folder**

### Overview

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/overview

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level. 
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV. title has white background therefore appears to be hidden. 
- [x] #426
- [x] HERO BANNER: update subtitle to an h3 and increase it's font size to --font-6. 
- [x] #538
- [x] #440
- [x] #437
- [x] #438
- [x] #439
- [x] 50-50: need a left gutter of left margin. Current text content is flush with left edge. Same for right variant.
- [x] #464
- [x] #466

### Capabilities / Indoor Positioning Navigation
_**All similar page layout**_

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/capabilities/indoor-data-collection
URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/capabilities/indoor-mapping-wayfinding
URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/capabilities/indoor-positioning-navigation

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level. 
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV. title has white background therefore appears to be hidden. 
- [x] HERO BANNER. update CTAs to one row. currently they are stacked or in two rows. 
- [x] HERO BANNER: update subtitle to an h3 and increase it's font size to --font-6. 
- [x] CONTENT BAR: allow author to choose background color for container block. 
- [x] #492
- [x] #514
- [x] 50-50: need a left gutter of left margin. Current text content is flush with left edge. Same for right variant. 
- [x] CONTENT SWITCHER: white text over white overlay. no contrast therefore hard to read. 
- [x] ELASTIC CONTENT STRIP: currently 1/3 of width of viewport. Needs to be 100%.
- [x] ELASTIC CONTENT STRIP: title and subtitle currently have hover effect. need it removed.
- [x] ELASTIC CONTENT STRIPT: blue calcite button needs to be a calcite link with arrow.
- [x] ELASTIC CONTENT STRIPT: subtitle needs to be white text.
- [x] FORM: hide form meta data.
