### ISSUE TITLE
Capabilities / GEOAI

### ISSUE THREAD

**Issue by jsavella** [Esri/esri-eds#387]
**Issues for all documents in the /capabilities/GEOAI/??? folder**

### Overview

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/geoai/overview

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level. 
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV. title has white background therefore appears to be hidden. 
- [x] HERO BANNER: Title needs a max-width of 500px. 
- [x] HERO BANNER: foreground image cropped on left and right sides. 
- [x] STORYTELLER: video url is visible, needs to be a foreground video. 
- [x] STORYTELLER:  first paragraph of content is indented or is not aligned with title. 
- [x] STORYTELLER: Content subtitles need to be an ordered list with '0' prefix. 
- [x] TEXT LINK STACK: reduce spacing between icon and title.
- [x] TEXT LINK STACK: update icon color from white to blue #009af2. 
- [x] #536
- [x] #537
- [x] MEDIA TEXT SPLIT: left image should not span 50% of page width. Add margin on all 4 sides of left image. 
- [x] CARD SIMPLE: card missing outer border.
- [x] CARD SIMPLE: hide url. 
- [x] CARD SIMPLE: update icon color from white to blue  #009af2. 
- [x] CARD SIMPLE: increase size of icon to 48x48px. 
- [x] FORM: hide form meta data.

**Comment by twhite313** [comment]
Remaining issues involving hero banner seem to be resolved. If not we can open new issues, but I'm not seeing major problems
