### ISSUE TITLE
Capabilities / Field Operations

### ISSUE THREAD

**Issue by jsavella** [Esri/esri-eds#392]
**Issues for all documents in the /capabilities/field-operations/??? folder**

### Overview

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/field-operations/overview

- [x] LOCAL NAV: Update logic to determine if page is an overview page. Don't traverse past this folder level. 
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV. title has white background therefore appears to be hidden. 
- [x] HERO BANNER: Title needs a max-width of 500px. 
- [x] HERO BANNER: foreground image cropped on left and right sides. 
- [x] CONTENT BAR: allow for content to take up 50% width along with top and bottom padding. 
- [x] #553
- [x] ICON TITLE SERIES: missing icon. 
- [x] ICON TITLE SERIES: Title same font-size as description below it. Needs to be h2. 
- [x] ICON TITLE SERIES: vertically align icon, title and description. 
- [x] #486
- [x] #485
- [x] #499
- [x] FORM: hide form meta data.

### Get Started

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/field-operations/get-started

- [x] LOCAL NAV: Update logic to determine if page is an overview page. Don't traverse past this folder level. 
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV. title has white background therefore appears to be hidden. 
- [x] HERO BANNER: Title needs a max-width of 500px. 
- [x] HERO BANNER: foreground image cropped on left and right sides. 
- [x] #453
- [x] CARD STANDARD: add card outline. 
- [x] CARD STANDARD: hide url. 
- [x] FORM: hide form meta data
