### ISSUE TITLE
Capabilities / 3D GIS 

### ISSUE THREAD

**Issue by jsavella** [Esri/esri-eds#394]
**Issues for all documents in the /capabilities/3d-gis/??? folder**

### Overview

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/3d-gis/overview

- [x] #408
- [x] #419
- [x] #415
- [x] #405
- [x] #432
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element. 
- [x] LOCAL NAV. title has white background therefore appears to be hidden. 
- [x] HERO BANNER: Title needs a max-width of 500px. 
- [x] #434
- [x] #421
- [x] #443
- [x] #447
- [x] #446
- [x] STORYTELLER: Content subtitles need to be an ordered list with '0' prefix. 
- [x] #445
- [x] STORYTELLER: video mp4 url is visible. Needs to be hidden. Don't see mp4 as background animated video. 
- [x] STORYTELLER: foreground image overlay text content is below foreground image. Should be within foreground.
- [x] Media Split: Anchor tag implementation 
- [x] #523
- [x] #540

### Resources

URL: https://main--esri-eds--esri.aem.live/en-us/capabilities/3d-gis/resources

- [x] LOCAL NAV: Update logic to determine if page has an overview page. Don't traverse past this folder level.
- [x] LOCAL NAV: menu titles expand beyond 1440px max inline width in desktop view. 
- [x] LOCAL NAV: mobile dropdown is hidden behind hero banner. 
- [x] LOCAL NAV: www has a blue 'Contact Sales' button. Need to add css to account for this authored element.
- [x] LOCAL NAV. title has white background therefore appears to be hidden. 
- [x] #451
- [x] 50-50: Left content 50% width and right image feature 50% width. 
- [x] #497
- [x] #496
- [x] ELASTIC CONTENT STRIP: need to expand to take up full width of viewport. 
- [x] ELASTIC CONTENT STRIP: title and subtitle currently have hover effect. need it removed. 
- [x] ELASTIC CONTENT STRIPT: blue calcite button needs to be a calcite link with arrow. 
- [x] ELASTIC CONTENT STRIPT: subtitle needs to be white text. 
- [x] TABS: local nav is visible to far right of tabs component. 
- [x] TABS: icons placement. centered and above title for each tab. 
- [x] TABS: cta must be left justified and line up with title/category and description above it. 
- [x] #535
- [x] CARD SIMPLE: card missing outer border. 
- [x] #534
- [x] CARD SIMPLE: update icon color from white to blue  #009af2. 
- [x] FORM: hide form meta data.

**Comment by twhite313** [comment]
@jsavella what does "Media Split: Anchor tag implementation" mean?
